name: serveurpaper1
version: 1.0
author: guillhome
main: fr.guillhome.serveurpaper1.Main
commands:
  test:
    description: Commande de test
    permission: test.use
  alert:
    description: commande de diffusion d'un message
    permission: perm.use